"""Add icon to Badge

Revision ID: 4f27d83b87f8
Revises: a75b772e6b8f
Create Date: 2025-05-29 00:26:37.672779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f27d83b87f8'
down_revision = 'a75b772e6b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
