"""upgrade

Revision ID: 8ffebdfa9f1f
Revises: d540fefd54e1
Create Date: 2025-05-29 00:58:16.418827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffebdfa9f1f'
down_revision = 'd540fefd54e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.drop_column('icon')

    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('badge', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
