"""update lastreminder columns

Revision ID: a75b772e6b8f
Revises: b5a949f51961
Create Date: 2025-05-21 12:01:54.936031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75b772e6b8f'
down_revision = 'b5a949f51961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_sent')

    # ### end Alembic commands ###
