name: Reminder Trigger

on:
  schedule:
    - cron: "*/5 * * * *" 
  workflow_dispatch:        

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Flask Reminder Route
        run: |
          curl -X GET https://habit-traveler-yfj5.onrender.com/send_reminders
