name: Reminder Trigger

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Flask Reminder Route
        run: |
          curl -X GET https://your-render-app.onrender.com/send_reminders
